### ISSUE TITLE
Clarify copyright holder

### ISSUE THREAD

**Issue by kmacdonaO** [dart-lang/clock#20]
I'm trying to figure out who the copyright holder is for this package.

CONTRIBUTING.md instructs contributors to us a copyright in the source files of:
    Copyright (c) 2017, the Dart project authors.
but the source files actually have copyrights for Google Inc., the pub spec has an author of "Dart Team", and the LICENSE file does not contain a copyright.  

Many open source packages have a copyright statement at the beginning of the LICENSE file which is what I'd suggest if possible.

Thanks

**Comment by flokau** [comment]
same here. It'd be much easier for the legal team and approval if this was available

**Comment by devoncarew** [comment]
Thanks for calling out the inconsistencies here!

The `author` field in the pubspec has since been removed (in favor of using pub.dev's publisher info). I'll update the contributing doc to indicate that new files in this repo should mirror the file copyright header of the existing files. For the license file, we do want to keep that a vanilla Apache license.

**Comment by devoncarew** [comment]
contributing.md updated in #38.
